// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_coord
String get_coord(String x);
RcppExport SEXP geoops_get_coord(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(get_coord(x));
    return rcpp_result_gen;
END_RCPP
}
// in_ring
bool in_ring(String pt, String ring);
RcppExport SEXP geoops_in_ring(SEXP ptSEXP, SEXP ringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< String >::type ring(ringSEXP);
    rcpp_result_gen = Rcpp::wrap(in_ring(pt, ring));
    return rcpp_result_gen;
END_RCPP
}
// inside_cpp
String inside_cpp(String point, String polygon);
RcppExport SEXP geoops_inside_cpp(SEXP pointSEXP, SEXP polygonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type point(pointSEXP);
    Rcpp::traits::input_parameter< String >::type polygon(polygonSEXP);
    rcpp_result_gen = Rcpp::wrap(inside_cpp(point, polygon));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP geoops_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_str
String rcpp_str(String x);
RcppExport SEXP geoops_rcpp_str(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_str(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json
String rcpp_json();
RcppExport SEXP geoops_rcpp_json() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_json());
    return rcpp_result_gen;
END_RCPP
}
