# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bearing <- function(start, end) {
    .Call('geoops_bearing', PACKAGE = 'geoops', start, end)
}

distance <- function(start, end, units) {
    .Call('geoops_distance', PACKAGE = 'geoops', start, end, units)
}

nearest <- function(target_point, points) {
    .Call('geoops_nearest', PACKAGE = 'geoops', target_point, points)
}

get_coords <- function(x) {
    .Call('geoops_get_coords', PACKAGE = 'geoops', x)
}

in_ring <- function(pt, ring) {
    .Call('geoops_in_ring', PACKAGE = 'geoops', pt, ring)
}

inside_cpp <- function(point, polygon) {
    .Call('geoops_inside_cpp', PACKAGE = 'geoops', point, polygon)
}

fart_cpp <- function(point, polygon) {
    .Call('geoops_fart_cpp', PACKAGE = 'geoops', point, polygon)
}

lineDistance <- function(line, units) {
    .Call('geoops_lineDistance', PACKAGE = 'geoops', line, units)
}

version <- function() {
    .Call('geoops_version', PACKAGE = 'geoops')
}

